---

- name: Invoke terraform backend module
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - inventories/default.yml
    - inventories/backend.yml
  roles:
    - role: backend
  tags: [ config, backend, megazord ]

- name: Invoke terraform network module
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - inventories/default.yml
    - inventories/network.yml
  roles:
    - role: network
  tags: [ config, network, megazord ]

...
